### ISSUE TITLE
Test Strategy: Create a test plan for the migration of integration test cases

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/cbuild2cmake#1]
Create a test plan for the migration of integration test cases. All aspects covered by current [Build Manager tests](https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/buildmgr/test/testinput) must be documented and equivalent go test cases must be implemented

**Comment by soumeh01** [comment]
Added a [Test Migration](https://github.com/Open-CMSIS-Pack/cbuild2cmake/wiki/cbuildgen-to-cbuild2cmake-test-migration) plans
