### ISSUE TITLE
Commit 8af6042 causes cyclic dependencies if multiple RunAlways targets exist

### ISSUE THREAD

**Issue by EaselinkBachmann** [Open-CMSIS-Pack/cbuild2cmake#227]
The recent commit cleaning up executes handling broke projects with multiple targets with an `always:` tag.

[Line 162](https://github.com/Open-CMSIS-Pack/cbuild2cmake/blob/8af6042495daa14890b1c6ccd536b91ab4253997/pkg/maker/buildcontent.go#L162) in buildcontent.go causes every executes statement with an `always:` tag to depend on every other executes statement with an `always` tag. This causes dependency cycles and breaks the generated CMakeLists.txt.

Otherwise that commits works really well, commenting out that line makes the build work fine.

**Comment by brondani** [comment]
@EaselinkBachmann Thanks for this finding. Could you please confirm that the proposed fix https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/228 also works correctly for your use cases?

**Comment by EaselinkBachmann** [comment]
> @EaselinkBachmann Thanks for this finding. Could you please confirm that the proposed fix #228 also works correctly for your use cases?

The fix works great! Thanks for the quick fix.

**Comment by EaselinkBachmann** [comment]
I noticed that `always` targets are now dependencies of every other target, regardless of which project they came from. In our case this is not much of an issue since our `always` steps are mostly pre-build steps and avoid modifying output files in case the content would be unchanged, but it is something to consider if creating such cross-project dependencies for every `always` target is intended.
