### ISSUE TITLE
Overall Approach to Implement CMake Support

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cbuild2cmake#7]
With `csolution` projects there are two different use-cases:
- (A) independent projects (simple single core project, unit test with many different test cases in separate cproject files)
- (B) dependent projects (secure/non-secure, multi-processor) where access sequences refer to outputs from other projects. These project require a context-set and it is assumed that [#1203](https://github.com/Open-CMSIS-Pack/devtools/issues/1203) and [1198](https://github.com/Open-CMSIS-Pack/devtools/issues/1198) is implemented as proposed. 

In all cases, each context of a `*.cproject.yml` file can be represented in one a `CMakeLists.txt` file. cmake that is stored in the related `tmp` directory.  

Build Dependency:
- For (A) the `CMakeLists.txt` file as a dependency to the `*.csolution.yml`, `*.cproject.yml`, and potentially `*.clayer.yml`.
- For (B) there is an additional dependency to the `*.build-set.yml` and potentially output files from other projects.

Priorities:

 1. Output `CMakeLists.txt` file for each context of a `*.cproject.yml` file. The `cbuild` command uses this with `CMake`.
 2. Implement the missing features (pre/post build steps, other file specific settings that cannot be represented in *.CPRJ)
 3. Add Build Dependencies to the `CMakeLists.txt` file and manage the `CMakeCache.txt` file in case of toolchain changes.
 4. Create a super `CMakeLists.txt` file that manages the overall build process.

**Comment by brondani** [comment]
I believe (B) type of projects don't necessarily require `context-set` - they could also be handled with regular context combinations.
For the sake of simplicity and predictability (e.g. "_what build configuration relates to a given build artifact on disk?_"), it has to be made clear we don't support multiple context-sets.

I would just have a higher priority for the super CMakeLists.txt that's an important piece, apart from that it doesn't deviate much from work packages plan [#1237](https://github.com/Open-CMSIS-Pack/devtools/issues/1237)

**Comment by brondani** [comment]
This requested/suggested approach is now complete.
Future lower priority `cbuild2cmake` enhancements are tracked in https://github.com/Open-CMSIS-Pack/devtools/issues/1645
